title: Best Server You Ever Seen For Testing
author: Gabriel
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I love everyone

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
